from . import cat_maintenance
from . import contracts
from . import insurance_policies
from . import mantenance_n_services
from . import payment_rent
from . import penaltys
from . import propertys
from . import res_partner
from . import tenancy